### PR TITLE
fix: mrgfy-1238 side menu not visible on small display

### PR DESCRIPTION
**Pull request by AlexandreGaubert**
Fixing menu not showing on small display in the mergify enterprise docs

### CODE REVIEW

**Comment by jd** [comment]
This seems to render something like this:
CleanShot 2022-07-26 at 10 45 43

Can we do something better if it's not too complicated?

**Comment by AlexandreGaubert** [comment]
I'll think of something better, but without the possibility to run the website myself for debug, I can't do something too complicated just with css

**Comment by AlexandreGaubert** [comment]
It should looks like this now 

image

image

**Comment by jd** [comment]
This looks great!

**Review by jd — APPROVED** [review]

**Pull request merged**
